var welcome_home = "<p id='front-side' onclick='myFunction()'>I'm glad you're here. Are you ready to learn?</p> <p id='back-side' onclick='myFunction_2()'>Always remember the wise words of Frederick Douglass: 'Knowledge makes a man unfit to be a slave.'</p>";

var absolute = "<p id='front-side' onclick='myFunction()'>Absolute</p> <p id='back-side' onclick='myFunction_2()'>The term absolute refers to the use of a word or phrase on its own when it would usually be accompanied by another word or phrase.<br><br> Examples: In the OED, absolute (abbreviated absol.) describes nouns which stand alone when they are usually used as modifiers. For example, NEW HALL n. is used as a modifier 'designating china or porcelain produced at New Hall, Shelton, Staffordshire', as in ‘New Hall porcelain is difficult to identify.’ New Hall can also occasionally be used on its own, not as a modifier, for example in 'four milk white cups and saucers which..might be early New Hall.' This use is described as 'Also absol.: New Hall ware.'<br><br>Similarly, Asperger's syndrome (at ASPERGER n.) can be abbreviated as Asperger's, as in 'people with Asperger's do struggle'; this use is described as 'in the genitive, used absol.'</p>";

var abstract = "<p id='front-side' onclick='myFunction()'>Abstract Noun</p> <p id='back-side' onclick='myFunction_2()'>An abstract noun denotes something immaterial such as an idea, quality, state, or action (as opposed to a concrete noun, which denotes a physical object, place, person, or animal).</p>";

var acc_case = "<p id='front-side' onclick='myFunction()'>Accusative Case</p> <p id='back-side' onclick='myFunction_2()'>In some inflected languages, the accusative case is used to indicate nouns and pronouns (as well as adjectives used to modify them) which function as the direct object of a verb.<br><br>Old English, which was an inflected language, possessed an accusative case, and it survived into the Middle English period, but then fell almost entirely out of use. The nearest equivalent in modern standard English, the objective case, is marked only in the objective pronouns me, him, etc., which are used as direct objects in sentences such as ‘I like him’. The objective pronouns reflect a merger of the accusative and dative forms.</p>";

var active_sent = "<p id='front-side' onclick='myFunction()'>Active Sentence or Clause</p> <p id='back-side' onclick='myFunction_2()'>In an active sentence or clause , the grammatical subject typically refers to the person or thing which carries out or causes the action expressed by the verb.<br><br> For example, ‘My dog broke your vase’, ‘The authorities will prosecute trespassers’, ‘John speaks Spanish’, and ‘The wind howled’ are all active sentences. Many types of active sentence can be converted into passives, for example ‘Your vase was broken by my dog’ (see passive).<br><br> The verb form used in an active clause is called an active verb: for example, broke is active whereas was broken is passive.</p>";

var adj = "<p id='front-side' onclick='myFunction()'>Adjective</p> <p id='back-side' onclick='myFunction_2()'>An adjective is a word expressing an attribute and qualifying a noun, noun phrase, or pronoun so as to describe it more fully. For example, the underlined words in the following are adjectives: the old man; a delicious piece of cake; nuclear weapons; she is sensible.<br><br> The category of adjectives is one of the parts of speech.</p>";

var adv = "<p id='front-side' onclick='myFunction()'>Adverb</p> <p id='back-side' onclick='myFunction_2()'>An adverb is a word which modifies the meaning of a verb, an adjective, another adverb, or a whole clause or sentence, and which typically expresses manner (e.g. he spoke quietly), degree (e.g. she is very clever), or a circumstance such as place, direction, or time (e.g. come here; they arrived yesterday).<br><br> In English, adverbs (especially adverbs of manner) are often formed from adjectives with the addition of the suffix -ly, e.g. angrily (from angry), nicely (from nice), and strangely (from strange). Some adverbs have the same form as the related adjective: for example, fast is an adjective in ‘a fast car’, and an adverb in ‘she drives fast’. <br><br> In English, adverbs of direction are frequently used with verbs to form phrasal verbs , for example run away, fall down, take off, heat up. Words like down, off, and up can also take noun phrases as complements, in which case they are prepositions: for example, down is an adverb in he fell down but a preposition in he fell down the stairs. <br><br> The category of adverbs is one of the parts of speech.</p>";

var adverbial = "<p id='front-side' onclick='myFunction()'>Adverbial | Adverbially</p> <p id='back-side' onclick='myFunction_2()'>If a word or phrase is adverbial, or is used adverbially, it is used as or like an adverb. <br><br> An adverbial is one of the five possible elements of a sentence or clause , the others being subject, verb, object, and complement. An adverbial frequently takes the form of an adverb (e.g. happily, often, there), adverb phrase (e.g. quite happily, very often, over there), or prepositional phrase (e.g. with happiness, at the weekend, on a bench). Like adverbs, adverbials typically express manner, time, or place. Adverbials are often optional, and their position in a sentence is usually flexible, as in ‘I visited my parents at the weekend’/‘At the weekend I visited my parents.’</p>";

var agree = "<p id='front-side' onclick='myFunction()'>Agree | Agreement </p> <p id='back-side' onclick='myFunction_2()'>Grammatical agreement refers to the fact of two (or more) elements in a clause or sentence having the same grammatical person, number, gender, or case. In modern English, the main type of agreement takes place between the subject and the verb of a clause. For example, in ‘This apple tastes delicious’, both the subject (This apple) and the verb (tastes) are in the singular form: they have singular agreement. In ‘These apples taste delicious’, both the subject (These apples) and the verb (taste) are in the plural form: they have plural agreement.<br><br> Sometimes a noun (or sense of a noun) has a plural form, but agrees with a singular verb. For example, in ‘Politics is interesting’, the plural noun politics is the subject of the singular verb form is: it has singular agreement. By contrast, in ‘His politics are fascistic’, politics is the subject of the plural verb form are: it has plural agreement.<br><br> In some varieties of English, collective nouns, which have a singular form but a collective meaning (for example audience, family, and team) may be used with either singular or plural agreement. For example, in British English it would be acceptable to say either ‘The team has lost’ (singular agreement) or ‘The team have lost’ (plural agreement); in American English, however, the latter is much less common.</p>";

var anaphoric = "<p id='front-side' onclick='myFunction()'>Anaphoric</p> <p id='back-side' onclick='myFunction_2()'>An anaphoric word or phrase is one which refers back to a word or phrase previously used in a text or conversation. Pronouns are frequently used anaphorically: for example, in ‘Clare arrived late, so I was really annoyed with her’, her is anaphoric, referring back to Clare.  A related term is cataphoric, which describes words or phrases which refer forward.</p>";

var antecedent = "<p id='front-side' onclick='myFunction()'>Antecedent</p> <p id='back-side' onclick='myFunction_2()'>An antecedent is a word or phrase which is referred back to by a pronoun or other pro-form. For example, in ‘Michael took the children with him’, Michael is the antecedent of the pronoun him. Specifically, an antecedent is a word or phrase referred back to by a relative pronoun or other relative word. For example, in ‘I went to get my coat, which I had left in the hall’, my coat is the antecedent of the relative pronoun which.</p>";

var anticipatory = "<p id='front-side' onclick='myFunction()'>Anticipatory</p> <p id='back-side' onclick='myFunction_2()'>In a sentence such as ‘It is nice to meet you’, it is the grammatical subject but stands in for or ‘anticipates’ the semantic subject, which is the clause ‘to meet you’: the sentence could be rephrased as ‘To meet you is nice’. When used in this way, it is described as anticipatory. The anticipated clause is typically an infinitive (as in ‘It is nice to meet you’) or a that-clause (as in ‘It is nice that you could come’).<br><br> It is sometimes used as an anticipatory object: that is, as a direct object which anticipates a following clause. For example, in ‘I took it that he wasn’t too happy about the prospect’, it anticipates the clause that he wasn’t too happy about the prospect.</p>";

var apodosisProtasis = "<p id='front-side' onclick='myFunction()'>Apodosis and Protasis</p> <p id='back-side' onclick='myFunction_2()'>Conditional sentences such as ‘If I had more money, I would buy it’ are made up of two clauses: one clause, which usually begins with if, expresses the condition (in this case, ‘If I had more money’) and the other clause expresses the consequence (in this case, ‘I would buy it’). The clause expressing the condition is called the protasis, and the clause expressing the consequence is called the apodosis.</p>";

var apposition = "<p id='front-side' onclick='myFunction()'>Apposition</p> <p id='back-side' onclick='myFunction_2()'>When two or more grammatical units (especially nouns or noun phrases) in a sentence refer to the same person or thing, and (typically) have the same role within the sentence, they are said to be in apposition. For example, in ‘Her father, the vicar, would have been shocked’, the noun phrases ‘Her father’ and ‘the vicar’ are in apposition: they refer to the same person, and both function as the subject of the sentence.</p>";

var appositive = "<p id='front-side' onclick='myFunction()'>Appositive</p> <p id='back-side' onclick='myFunction_2()'>An appositive compound is one in which the compound ‘X-Y’ means ‘both X and Y’ (i.e. the two elements are in apposition). Such compounds can be either nouns or adjectives.</p>";

var article = "<p id='front-side' onclick='myFunction()'>Article</p> <p id='back-side' onclick='myFunction_2()'>An article is one of a small set of words (in English, the, a, and an) which limit the application of nouns. Articles are either definite or indefinite. The main function of the definite article (in English, the) is to specify the noun given, while the indefinite article (in English, a or an) marks a noun as being generic.</p>";

var attributive = "<p id='front-side' onclick='myFunction()'>Attributive</p> <p id='back-side' onclick='myFunction_2()'>An attributive adjective directly modifies a noun or noun phrase, usually preceding it (e.g. ‘a warm day’) but sometimes following it as a postmodifier (e.g. ‘the astronomer royal’). Attributive adjectives are contrasted with predicative adjectives, which are linked to a noun or noun phrase by a verb (e.g. ‘the day was warm’).</p>";

var auxiliary = "<p id='front-side' onclick='myFunction()'>Auxiliary verb | Auxiliary</p> <p id='back-side' onclick='myFunction_2()'>An auxiliary verb is one of a small category of verbs which have a grammatical rather than a lexical role; they are used in combination with other verbs, for example to form particular tenses and constructions. For instance, have is an auxiliary verb (forming the perfect) in ‘They have sold their house’, where it is used in combination with the main verb sold. By contrast, have is a main verb in ‘They have a lovely house’, where it has lexical meaning (‘own, possess’) and is not used to support another verb.<br><br> In English, the primary auxiliary verbs are be, have, and do; modal verbs such as can, must, etc., are also a type of auxiliary verb.<br><br> An auxiliary verb is sometimes referred to simply as an auxiliary.</p>";

var case = "<p id='front-side' onclick='myFunction()'>Case</p> <p id='back-side' onclick='myFunction_2()'>A case is an inflected form of a noun, pronoun, or adjective which expresses its grammatical relationship with other words. For example, the fact that a noun is in the nominative case indicates that it is the subject of the verb.</p>";

var baseForm = "<p id='front-side' onclick='myFunction()'>Base Form</p> <p id='back-side' onclick='myFunction_2()'>The base form of a verb is the form without any inflections: for example, walk is the base form, and the inflected forms are walked, walks, and walking.</p>";




var myArray = [welcome_home, absolute, abstract, acc_case, active_sent, adj, adv, adverbial, agree, anaphoric, antecedent, anticipatory, apodosisProtasis, apposition, appositive, article, attributive, auxiliary, case, baseForm];

var randomItem = myArray[Math.floor(Math.random()*myArray.length)];

document.getElementById("demo").innerHTML = randomItem;

function GetValue() {
	var randomItem = myArray[Math.floor(Math.random()*myArray.length)];
	document.getElementById("demo").innerHTML = randomItem;
}

function myFunction() {
    document.getElementById("back-side").style.display = "block ";
    document.getElementById("front-side").style.display = "none ";
}

function myFunction_2() {
    document.getElementById("back-side").style.display = "none ";
    document.getElementById("front-side").style.display = "block ";
}