var redirect = "<p id='front-side' onclick='myFunction()'>301 redirect</p> <p id='back-side' onclick='myFunction_2()'>Redirection happens when you visit one specific page and immediately after that you're being automatically redirected to a different page (with a different URL).<br>Essentially, there are two types of redirection: temporary and permanent. From a user's perspective there's no difference between them, but there is one from a search engine's perspective. 301 redirect is a permanent redirection. It informs search engines that the page they're trying to access has changed its address permanently. This means that whatever rankings the page already has should be transferred to the new address (this doesn't happen with a temporary redirection).</p>";

var Google_Ads = "<p id='front-side' onclick='myFunction()'>Google Ads</p> <p id='back-side' onclick='myFunction_2()'>Google Ads (previously Google AdWords, before July 24, 2018) is an online advertising platform developed by Google, where advertisers pay to display brief advertisements, service offerings, product listings, video content and generate mobile application installs within the Google ad network to web users. Google Ads' system is based partly on cookies and partly on keywords determined by advertisers. Google uses these characteristics to place advertising copy on pages where they think it might be relevant. Advertisers pay when users divert their browsing to click on the advertising copy. Partner websites receive a portion of the generated income. Google Ads involves Pay Per CLick nad Paid Advertising</p>";

var Affiliate = "<p id='front-side' onclick='myFunction()'>Affiliate </p> <p id='back-side' onclick='myFunction_2()'>An affiliate site markets products or services that are actually sold by another website or business in exchange for fees or commissions.</p>";

var algorithm = "<p id='front-side' onclick='myFunction()'>Algorithm</p> <p id='back-side' onclick='myFunction_2()'>A program used by search engines to determine what pages to suggest for a given search query.<br> In mathematics and computer science, an algorithm is an unambiguous specification of how to solve a class of problems. Algorithms can perform calculation, data processing and automated reasoning tasks.</p>";

var alt_text = "<p id='front-side' onclick='myFunction()'>Alt Text</p> <p id='back-side' onclick='myFunction_2()'>A description of a graphic, which usually isn't displayed to the end user, unless the graphic is undeliverable, or a browser is used that doesn't display graphics. <br>Alt text is important because search engines can't tell one picture from another. Alt text is the one place where it is acceptable for the spider to get different content than the human user, but only because the alt text is accessible to the user, and when properly used is an accurate description of the associated picture. <br>Special web browsers for visually challenged people rely on the alt text to make the content of graphics accessible to the users.</p>";

var Google_Analytics = "<p id='front-side' onclick='myFunction()'>(Google) Analytics</p> <p id='back-side' onclick='myFunction_2()'>A program which assists in gathering and analyzing data about website usage. Google analytics is a feature rich, popular, free analytics program. <br> Analytics is the discovery, interpretation, and communication of meaningful patterns in data and applying those patterns towards effective decision making. In other words, analytics can be understood as the connective tissue between data and effective decision making, within an organization.</p>";

var anchor_text = "<p id='front-side' onclick='myFunction()'>Anchor Text</p> <p id='back-side' onclick='myFunction_2()'>Every link consists of two main elements. There's the web address that the link is pointing to (the destination) and there's the anchor text. The anchor text is the text that works as the link. <br>The easiest way of explaining this is to give you an example. Here's a link to my resource and education page: online business resources. The destination of this link is http://newinternetorder.com/tools/, and the anchor text is 'online business resources'.<br> Anchor texts are particularly important for SEO. Whenever you're trying to get a link back to your website it's good to have a relevant keyword as the anchor text.</p>";

var astroturfing = "<p id='front-side' onclick='myFunction()'>Astroturfing</p> <p id='back-side' onclick='myFunction_2()'>(the opposite of full disclosure) Attempting to advance a commercial or political agenda while pretending to be an impartial grassroots participant in a social group. Participating in a user forum with the secret purpose of branding, customer recruitment, or public relations.</p>";

var authority_site = "<p id='front-side' onclick='myFunction()'>Authority Site</p> <p id='back-side' onclick='myFunction_2()'>A website which has many incoming links from other related expert/hub sites. Because of this simultaneous citation from trusted hubs an authority site usually has high trust, pagerank, and search results placement. Wikipedia, is an example of an authority site.</p>";

var b2b_b2c = "<p id='front-side' onclick='myFunction()'>B2B and B2C</p> <p id='back-side' onclick='myFunction_2()'>Business-to-business is a situation where one business makes a commercial transaction with another. This typically occurs when: A business is sourcing materials for their production process. A business needs the services of another for operational reasons. A business re-sells goods and services produced by others.<br>More recently, the term B2C refers to the online selling of products, or e-tailing, in which manufacturers or retailers sell their products to consumers over the Internet. It is one of four categories of e-commerce, along with B2B (business to business), C2B (customer to business) and C2C (customer to customer)</p>";

var backlink_word = "<p id='front-side' onclick='myFunction()'>Backlink </p> <p id='back-side' onclick='myFunction_2()'>An incoming hyperlink from one web page to another website.<</p>";

var black_hat_seo = "<p id='front-side' onclick='myFunction()'>Black Hat SEO</p> <p id='back-side' onclick='myFunction_2()'>Black hat SEO is the name for all SEO practices that are known for being manipulative or unethical, and in the long run can hurt your website, or even get it banned from search engines.</p>";

var blog = "<p id='front-side' onclick='myFunction()'>Blog</p> <p id='back-side' onclick='myFunction_2()'>A website which presents content in a more or less chronological series. Content may or may not be time sensitive. Most blogs us a Content Management System such as WordPress rather than individually crafted WebPages. Because of this, the Blogger can chose to concentrate on content creation instead of arcane code.</p>";

var bot = "<p id='front-side' onclick='myFunction()'>Bot (robot, spider, crawler)</p> <p id='back-side' onclick='myFunction_2()'>A program which performs a task more or less autonomously. Search engines use bots to find and add web pages to their search indexes. Spammers often use bots to 'scrape' content for the purpose of plagiarizing it for exploitation by the Spammer.</p>";

var bounce_rate = "<p id='front-side' onclick='myFunction()'>Bounce Rate</p> <p id='back-side' onclick='myFunction_2()'>The percentage of users who enter a site and then leave it without viewing any other pages.</p>";

var bread_crumbs = "<p id='front-side' onclick='myFunction()'>Bread Crumbs</p> <p id='back-side' onclick='myFunction_2()'>Web site navigation in a horizontal bar above the main content which helps the user to understand where they are on the site and how to get back to the root areas.</p>";

var canonical_tag = "<p id='front-side' onclick='myFunction()'>Canonical Tag</p> <p id='back-side' onclick='myFunction_2()'>It's an HTML link element that lets webmasters to inform search engines about some duplicate content pages they've created. The tag is placed in the HEAD section of the HTML structure. Here's what it looks like:<br>link rel='canonical' href='http://www.example.com/'<br>This tag informs that the current page is a copy of the page located under the address set in the canonical tag (href).<br>The main idea is that when a search engine sees this tag it does not rank that page, but transfers all the rankings to the canonical page. So in essence it's very similar to the 301 redirect.</p>";

var click_fraud = "<p id='front-side' onclick='myFunction()'>Click Fraud</p> <p id='back-side' onclick='myFunction_2()'>Improper clicks on a PPC advertisement usually by the publisher or his minions for the purpose of undeserved profit. Click fraud is a huge issue for add agencies like Google, because it lowers advertiser confidence that they will get fair value for their add spend.</p>";

var cloaking = "<p id='front-side' onclick='myFunction()'>Cloaking</p> <p id='back-side' onclick='myFunction_2()'>It's a practice of taking a webpage and building it in a way so it displays different content to people and to search engines. That way, at least in theory, you can get good ranking for your desired keywords (by presenting an optimized page to the spiders) and then present real people with unrelated offers and content. While this might work from a marketing standpoint it can also get you penalized or even banned very quickly.</p>";

var cms_crm = "<p id='front-side' onclick='myFunction()'>CMS and CRM</p> <p id='back-side' onclick='myFunction_2()'>Content Management System - Programs such as Wordpress, which separate most of the mundane Webmaster tasks from content creation so that a publisher can be effective without acquiring or even understanding sophisticated coding skills if they so chose.<br>Customer-relationship management is an approach to manage a company's interaction with current and potential customers. It uses data analysis about customers' history with a company to improve business relationships with customers, specifically focusing on customer retention and ultimately driving sales growth.</p>";

var code_swapping = "<p id='front-side' onclick='myFunction()'>Code Swapping</p> <p id='back-side' onclick='myFunction_2()'>Code swapping is submitting a text-only version of a web page to the search engines in an effort to gain high rankings for that page. Once the desired positions within the search engines are achieved, the search engine-friendly text page is swapped out for a content page designed for human visitors.</p>";

var comment_spam = "<p id='front-side' onclick='myFunction()'>Comment Spam</p> <p id='back-side' onclick='myFunction_2()'>Posting blog comments for the purpose of generating an inlink to another site. The reason many blogs use link condoms.</p>";

var conversion_rate = "<p id='front-side' onclick='myFunction()'>Conversion Rate Optimization (CRO)</p> <p id='back-side' onclick='myFunction_2()'>Conversion rate optimization (CRO) is the systematic process of increasing the percentage of website visitors who take a desired action - be that filling out a form, becoming customers, or otherwise.</p>";

var conversion = "<p id='front-side' onclick='myFunction()'>Conversion</p> <p id='back-side' onclick='myFunction_2()'>Conversion is often associated with a sale, but in online marketing, defining conversion just by that is too narrow-minded. Conversion, the way we define it, happens every time a visitor completes a desired action on your website. That could be a click-through to the next page if that is your main goal on a certain page. It could be the subscription to a newsletter. And it could be a visitor buying your product. In short: conversion happens when someone completes the action you want them to complete.</p>";

var cpc = "<p id='front-side' onclick='myFunction()'>Cost Per Click</p> <p id='back-side' onclick='myFunction_2()'>Cost Per Click (CPC) refers to the actual price you pay for each click in your pay-per-click (PPC) marketing campaigns</p>";

var cpm = "<p id='front-side' onclick='myFunction()'>CPM (Cost Per Thousand impressions)</p> <p id='back-side' onclick='myFunction_2()'>A statistical metric used to quantify the average value / cost of Pay Per Click advertisements. M - from the Roman numeral for one thousand.<br>Cost per thousand, also called cost per mille, is a marketing term used to denote the price of 1,000 advertisement impressions on one webpage. If a website publisher charges $2.00 CPM, that means an advertiser must pay $2.00 for every 1,000 impressions of its ad.</p>";

var directory = "<p id='front-side' onclick='myFunction()'>Directory</p> <p id='back-side' onclick='myFunction_2()'>In computing, a directory is a file system cataloging structure which contains references to other computer files, and possibly other directories. On many computers, directories are known as folders, or drawers, analogous to a workbench or the traditional office filing cabinet.</p>";

var doorway = "<p id='front-side' onclick='myFunction()'>Doorway</p> <p id='back-side' onclick='myFunction_2()'>Doorway pages are web pages that are created for the deliberate manipulation of search engine indexes. A doorway page will affect the index of a search engine by inserting results for particular phrases while sending visitors to a different page.<br>A web page that is designed specifically to attract traffic from a search engine. A doorway page which redirects users (but not spiders) to another site or page is implementing cloaking.</p>";

var duplicate_content = "<p id='front-side' onclick='myFunction()'>Duplicate Content</p> <p id='back-side' onclick='myFunction_2()'>If you have two separate pages within your website that have the same content on them (or very similar content) then you have duplicate content. Duplicate content is believed to be a bad thing for SEO. Google doesn't like sites that use the same piece of content over and over again, and they often penalize them for it.<br>If you think that you are safe then think again. Let me give you an example. If your site runs on WordPress, and if you're using similar categories and tags (like for example a tag 'business' and a category 'business') then the listing pages for your tags and categories will probably be very similar if not exactly the same. That is a prime example of duplicate content.</p>";

var feed = "<p id='front-side' onclick='myFunction()'>Feed</p> <p id='back-side' onclick='myFunction_2()'>Content which is delivered to the user via special websites or programs such as news aggregators</p>";

var link_farm = "<p id='front-side' onclick='myFunction()'>Link Farm or Free For All</p> <p id='back-side' onclick='myFunction_2()'>A page or site with many outgoing links to unrelated websites, containing little if any unique content. Link farms are only intended for spiders, and have little if any value to human users, and thus are ignored or penalized by the search engines<br>It's a network of websites that link to each other for the sole purpose of increasing their rankings and PageRanks. Let me give you an example. If you ware to create a link farm (don't!) you could launch 4 different websites, for example. Each on a different server. Then you would link page #1 to pages #2, #3, #4. Page #2 to pages #1, #3, #4, and so on. Basically, every page links to every other page. Such a network isn't very powerful when it contains only 4 sites, but when they're hundreds or thousands of them (which isn't uncommon) then it's a completely different story. BUT!<br>This is considered as a 'black hat' SEO technique. Don't take part in it unless you want your site to get penalized.</p>";

var frames = "<p id='front-side' onclick='myFunction()'>Frames</p> <p id='back-side' onclick='myFunction_2()'>An inline frame is used to embed another document within the current HTML document.<br>A web page design where two or more documents appear on the same screen, each within it's own frame. Frames are bad for SEO because spiders sometimes fail to correctly navigate them. Additionally, most users dislike frames because it is almost like having two tiny monitors neither of which shows a full page of information at one time.</p>";

var gizmo = "<p id='front-side' onclick='myFunction()'>Gizmo (gadget, widget)</p> <p id='back-side' onclick='myFunction_2()'>Small applications used on web pages to provide specific functions such as a hit counter or IP address display. Gizmos can make good link bait.</p>";

var google_bomb = "<p id='front-side' onclick='myFunction()'>Google Bomb</p> <p id='back-side' onclick='myFunction_2()'>an attempt to make a search term return a website for an unexpected person or organization when entered in a search engine (typically for satirical or humorous purposes) by the creation of numerous links to that website from pages including the search term.</p>";

var google_bowling = "<p id='front-side' onclick='myFunction()'>Google Bowling</p> <p id='back-side' onclick='myFunction_2()'>Google Bowling means Manipulating the external ranking factors that Google uses to penalize a site against your competitors (or someone you just don't like or want to appear in the SERPs). There is one thing that protects a website against Google Bowling - a solid back link profile of its own.</p>";

var google_dance = "<p id='front-side' onclick='myFunction()'>Google Dance</p> <p id='back-side' onclick='myFunction_2()'>The change in SERPs caused by an update of the Google database or algorithm. The cause of great angst and consternation for webmasters who slip in the SERPs. Or, the period of time during a Google index update when different data centers have different data.</p>";

var google_juice = "<p id='front-side' onclick='myFunction()'>Google Juice</p> <p id='back-side' onclick='myFunction_2()'>Google juice (trust, authority, pagerank) trust / authority from Google, which flows through outgoing links to other pages.</p>";

var hit = "<p id='front-side' onclick='myFunction()'>Hit</p> <p id='back-side' onclick='myFunction_2()'>Once the standard by which web traffic was often judged, but now a largely meaningless term replaced by pageviews AKA impressions. A hit happens each time that a server sends an object - documents, graphics, include files, etc. Thus one pageview could generate many hits.</p>";

var hub = "<p id='front-side' onclick='myFunction()'>Hub</p> <p id='back-side' onclick='myFunction_2()'>Hub (expert page) a trusted page with high quality content that links out to related pages.</p>";

var HTML = "<p id='front-side' onclick='myFunction()'>HTML</p> <p id='back-side' onclick='myFunction_2()'>(Hyper Text Markup Language) directives or 'markup' which are used to add formatting and web functionality to plain text for use on the internet. HTML is the mother tongue of the search engines, and should generally be strictly and exclusively adhered to on web pages.</p>";

var impressions = "<p id='front-side' onclick='myFunction()'>Impresisons</p> <p id='back-side' onclick='myFunction_2()'>The amount of impressions is the amount of times that an advertisement has been shown (through Google AdWords or other forms of PPC advertising) or a webpage has been listed on a SERP (Search Engine Results Page, in the case of search engine optimization).<br>Note that the amount of impressions differs from the amount of times that an advertisement is actually seen. Impressions can be shown 'under the fold'. This means that visitors have to scroll down to be able to see the advertisement. This significantly increases the amount of advertisements that are never seen by a potential customer.<br>Within Google Adwords you are able to exclude impressions that are shown under the fold. This is often recommended by Google AdWords professionals, especially for CPM-campaigns.</p>";

var inbound_link = "<p id='front-side' onclick='myFunction()'>Inbound Links</p> <p id='back-side' onclick='myFunction_2()'>inbound link (inlink, incoming link) Inbound links from related pages are the source of trust and pagerank.</p>";

var index = "<p id='front-side' onclick='myFunction()'>Index (Noun and Verb)</p> <p id='back-side' onclick='myFunction_2()'>index Noun - a database of WebPages and their content used by the search engines.<br>index Verb - to add a web page to a search engine index.</p>";

var indexed_pages = "<p id='front-side' onclick='myFunction()'>Indexed Pages</p> <p id='back-side' onclick='myFunction_2()'>The pages on a site which have been indexed.</p>";

var keyword = "<p id='front-side' onclick='myFunction()'>Keyword abd key phrase</p> <p id='back-side' onclick='myFunction_2()'>Keywords are single words or whole phrases of a particular SEO importance for a given page or website.<br> Keywords are also the word or phrase that a user enters into a search engine.</p>";

var keyword_cannibalization = "<p id='front-side' onclick='myFunction()'>Keyword Cannibalization</p> <p id='back-side' onclick='myFunction_2()'>The excessive reuse of the same keyword on too many web pages within the same site. This practice makes it difficult for the users and the search engines to determine which page is most relevant for the keyword.</p>";

var keyword_density = "<p id='front-side' onclick='myFunction()'>Keyword Density</p> <p id='back-side' onclick='myFunction_2()'>Keyword density is a number describing how often does a specific phrase appear in a piece of text. To calculate it you just have to divide the number of times your keyword appears in a piece of text by the total number of words this piece of text has, and then multiply the result by 100. The final result will be expressed as a percentage score.<br>Keyword density is believed to have an effect on SEO. The reasoning behind it is that if a given phrase has a high density score then it means that the text is clearly about that phrase, so it probably should get good rankings for it. Unfortunately this practice doesn't work so well like it used to in the past.</p>";

var keyword_research = "<p id='front-side' onclick='myFunction()'>Keyword Research</p> <p id='back-side' onclick='myFunction_2()'>The hard work of determining which keywords are appropriate for targeting.</p>";

var keyword_stuffing = "<p id='front-side' onclick='myFunction()'>Keyword Stuffing</p> <p id='back-side' onclick='myFunction_2()'>If you take a random piece of text in English some words will occur more frequently than the other. For example, words like: and, or, it occur very frequently, while words like: powerhouse, mushrooming occur very rarely. Keyword stuffing is a practice of taking a word or a phrase and repeating it very often in a piece of text. Usually to the point where the text no longer looks natural, all for the purpose of increasing keyword density of your desired phrase.<br>While working on keyword density is no longer believed to work, keyword stuffing does work, but it works against you. Stuffing your text with keywords is sure to backfire.</p>";

var landing_page = "<p id='front-side' onclick='myFunction()'>Landing Page</p> <p id='back-side' onclick='myFunction_2()'>landing page is the page that a user lands on when they click on a link in a SERP</p>";

var lsi = "<p id='front-side' onclick='myFunction()'>Latent Semantic Indexing (LSI)</p> <p id='back-side' onclick='myFunction_2()'>The standard definition of LSI is truly impossible to understand so I'm not going to bring it up here. Instead here's a more digestible one.<br>LSI is considered to be an important factor for search engines when ranking your page. It's said that search engines analyze the content on your page and search for LSI keywords supporting your main keyword. If they find such keywords your page gets a boost in rankings for your main keyword.<br>LSI keywords are keywords that are similar to your main one - keywords that are usually found along your main keyword in the natural language.<br>For example, if your main keyword is 'gardening equipment' and you're using it a lot in your article it would be great to use some LSI keywords as well, such as: 'plants', 'garden', 'vegetables', 'planting', etc. These are the keywords that would be mentioned naturally in a genuine conversation.<br>In other words, LSI is a way of checking whether the text is genuine or just stuffed with random keywords purely for improving rankings.<br>latent semantic indexing (LSI) This mouthful just means that the search engines index commonly associated groups of words in a document. SEOs refer to these same groups of words as 'Long Tail Searches'. The majority of searches consist of three or more words strung together. See also 'long tail'. The significance is that it might be almost impossible to rank well for 'mortgage', but fairly easy to rank for 'second mortgage to finance monster truck team'. Go figure.</p>";

var link = "<p id='front-side' onclick='myFunction()'>Link</p> <p id='back-side' onclick='myFunction_2()'>An element on a web page that can be clicked on to cause the browser to jump to another page or another part of the current page.</p>";

var link_bait = "<p id='front-side' onclick='myFunction()'>Link Bait</p> <p id='back-side' onclick='myFunction_2()'>A webpage with the designed purpose of attracting incoming links, often mostly via social media.</p>";

var link_building = "<p id='front-side' onclick='myFunction()'>Link Building</p> <p id='back-side' onclick='myFunction_2()'>This is one of the biggest SEO terms. Link building is simply a process of getting backlinks to your page. For example, if you're publishing articles on ezinearticles.com with a link to your site then you're doing some link building.<br>One more thing. Link building is considered to be the most important element of every SEO strategy. If you want to have a well ranked page you have to get backlinks to it.</p>";

var Link_Condom = "<p id='front-side' onclick='myFunction()'>Link Condom</p> <p id='back-side' onclick='myFunction_2()'>Any of several methods used to avoid passing link love to another page, or to avoid possible detrimental results of indorsing a bad site by way of an outgoing link, or to discourage link spam in user generated content.</p>";

var linkerati = "<p id='front-side' onclick='myFunction()'>Linkerati </p> <p id='back-side' onclick='myFunction_2()'>Internet users who are the most productive targets of linkbait. The Linkerati includes - social taggers, forum posters, resource maintainers, bloggers and other content creators, etc - who are most likely to create incoming links or link generating traffic (in the case of social networkers). </p>";

var link_exchange = "<p id='front-side' onclick='myFunction()'>Link Exchange</p> <p id='back-side' onclick='myFunction_2()'>A reciprocal linking scheme often facilitated by a site devoted to directory pages. Link exchanges usually allow links to sites of low or no quality, and add no value themselves. Quality directories are usually human edited for quality assurance.</p>";

var link_love = "<p id='front-side' onclick='myFunction()'>Link Love</p> <p id='back-side' onclick='myFunction_2()'>An outgoing link, which passes trust, unencumbered by any kind of link condom.</p>";

var link_partner = "<p id='front-side' onclick='myFunction()'>Link Partner</p> <p id='back-side' onclick='myFunction_2()'>(link exchange, reciprocal linking) Two sites which link to each other. Search engines usually don't see these as high value links, because of the reciprocal nature.</p>";

var link_popularity = "<p id='front-side' onclick='myFunction()'>Link Popularity</p> <p id='back-side' onclick='myFunction_2()'>A measure of the value of a site based upon the number and quality of sites that link to it</p>";

var long_tail = "<p id='front-side' onclick='myFunction()'>Long Tail Keywords</p> <p id='back-side' onclick='myFunction_2()'>Long tail keywords are those three and four keyword phrases which are very, very specific to whatever you are selling. You see, whenever a customer uses a highly specific search phrase, they tend to be looking for exactly what they are actually going to buy.<br>Longer more specific search queries that are often less targeted than shorter broad queries. For example a search for 'widgets' might be very broad while 'red widgets with reverse threads' would be a long tail search. A large percentage of all searches are long tail searches/</p>";

var mashups = "<p id='front-side' onclick='myFunction()'>Mashups</p> <p id='back-side' onclick='myFunction_2()'>A web page which consists primarily of single purpose software and other small programs (gizmos and gadgets) or possibly links to such programs. Mashups are quick and easy content to produce and are often popular with users, and can make good link bait. Tool collection pages are sometimes mashups.</p>";

var meta_tags = "<p id='front-side' onclick='myFunction()'>META tags</p> <p id='back-side' onclick='myFunction_2()'>Statements within the HEAD section of an HTML page which furnishes information about the page. META information may be in the SERPs but is not visible on the page. It is very important to have unique and accurate META title and description tags, because they may be the information that the search engines rely upon the most to determine what the page is about. Also, they are the first impression that users get about your page within the SERPs.</p>";

var metric = "<p id='front-side' onclick='myFunction()'>Metric</p> <p id='back-side' onclick='myFunction_2()'>A standard of measurement used by analytics programs.</p>";

var mirror_site = "<p id='front-side' onclick='myFunction()'>Mirror Site</p> <p id='back-side' onclick='myFunction_2()'>An identical site at a different address.</p>";

var monetize = "<p id='front-side' onclick='myFunction()'>Monetize</p> <p id='back-side' onclick='myFunction_2()'>To extract income from a site. Adsense ads are an easy way to Monetize a website.</p>";

var natural_search_results = "<p id='front-side' onclick='myFunction()'>Natural Search Results</p> <p id='back-side' onclick='myFunction_2()'>The search engine results which are not sponsored, or paid for in any way.</p>";

var nofollow = "<p id='front-side' onclick='myFunction()'>nofollow</p> <p id='back-side' onclick='myFunction_2()'>A command found in either the HEAD section of a web page or within individual link code, which instructs robots to not follow either any links on the page or the specific link. A form of link condom.</p>";

var noindex = "<p id='front-side' onclick='myFunction()'>noindex</p> <p id='back-side' onclick='myFunction_2()'>A command found in either the HEAD section of a web page or within individual link code, which instructs robots to not index the page or the specific link. A form of link condom.</p>";

var non_reciprocal_link = "<p id='front-side' onclick='myFunction()'>non reciprocal link</p> <p id='back-side' onclick='myFunction_2()'>non reciprocal link if site A links to site B, but site B does not link back to site A, then the link is considered non reciprocal. Search engines tend to give more value to non-reciprocal links than to reciprocal ones because they are less likely to be the result of collusion between sites.</p>";

var organic_link = "<p id='front-side' onclick='myFunction()'>Organic Link</p> <p id='back-side' onclick='myFunction_2()'>An organic link is a link from someone else's website, blog or social account where they linked to your site without being asked to. You had nothing to do with this other than provide great content that they felt was worth sharing with their readers and/or followers.</p>";

var pagerank = "<p id='front-side' onclick='myFunction()'>PageRank</p> <p id='back-side' onclick='myFunction_2()'>PageRank or PR is an algorithm first created by Larry Page (one of two founding fathers of Google) to calculate (although 'estimate' might be a better word here) the importance of a given website. No one is 100% certain about how it actually works or what all the factors are because Google is not very open in that matter. However, one of commonly believed opinions are that one of the deciding factors is the number of backlinks a site has and the PageRanks of the sites linking to it. So basically, the more links you have, and the better PageRank these linking sites have the better your PageRank will be.<br>It's not surprising but pages with highest PageRanks are usually ones that are highly recognizable and popular around the internet. For example, Google.com itself has a PR of 10. Facebook is PR9 website. Yahoo - PR9.</p>";

var paid_inclusion = "<p id='front-side' onclick='myFunction()'>Paid Inclusion</p> <p id='back-side' onclick='myFunction_2()'>Paid inclusion is a search engine marketing product where the search engine company charges fees related to inclusion of websites in their search index. The use of paid inclusion is controversial and paid inclusion's popularity has decreased over time among search engines.</p>";

var portal = "<p id='front-side' onclick='myFunction()'>Portal</p> <p id='back-side' onclick='myFunction_2()'>A web service which offers a wide array of features to entice users to make the portal their 'home page' on the web. IGoogle, Yahoo, and MSN are portals.</p>";

var PPA = "<p id='front-side' onclick='myFunction()'>PPA (Pay Per Action)</p> <p id='back-side' onclick='myFunction_2()'>Very similar to Pay Per Click except publishers only get paid when click throughs result in conversions.</p>";

var PPC = "<p id='front-side' onclick='myFunction()'>PPC (Pay Per Click)</p> <p id='back-side' onclick='myFunction_2()'>PPC (Pay Per Click) a contextual advertisement scheme where advertisers pay add agencies (such as Google) whenever a user clicks on their add. Adwords is an example of PPC advertising.</p>";

var Proprietary_Method = "<p id='front-side' onclick='myFunction()'>Proprietary Method</p> <p id='back-side' onclick='myFunction_2()'>Proprietary method (bullshit, snake oil) sales term often used by SEO service providers to imply that they can do something unique to achieve 'Top Ten Rankings'.</p>";

var RLT = "<p id='front-side' onclick='myFunction()'>Regional Long Tail (RLT)</p> <p id='back-side' onclick='myFunction_2()'>Regional long tail (RLT) coined by Chris Paston of onlinedevelopment.co.uk - a multi word keyword term which contains a city or region name. Especially useful for the service industry.</p>";

var robots = "<p id='front-side' onclick='myFunction()'>Robots.txt</p> <p id='back-side' onclick='myFunction_2()'>This is a file. One that's particularly important for SEO. It notifies the search engines which areas of your blog are restricted for them. Restricting search engines from accessing some of your pages might not sound that tempting at first but in fact it's a valuable thing. First of all, you can exclude all your admin pages from indexing (for example, pages in the wp-admin section of your WordPress blog). You can also use it to prevent search engines from seeing duplicate content on your site. What you do, for example, is prevent them from accessing the category listings on your blog, so only the tag listings are indexed, or the other way around. Very useful file. You can (and should) learn more about it here:</p>";

var ROI = "<p id='front-side' onclick='myFunction()'>Return on Investment (ROI)</p> <p id='back-side' onclick='myFunction_2()'>ROI (Return On Investment) One use of analytics software is to analyze and quantify return on investment, and thus cost / benefit of different schemes.</p>";

var sandbox = "<p id='front-side' onclick='myFunction()'>Sandbox, supplemental index</p> <p id='back-side' onclick='myFunction_2()'>Google is believed to have a second index called the sandbox (or the supplemental index). Not every new page appears in the main index straight away. Some of them are put into the sandbox until Google decides that they are worthy of appearing in the main index - the one you see whenever you do a standard search on Google. Websites that are placed in the sandbox don't appear for normal searches. This means that being in the sandbox is the worst that can happen to your site.</p>";

var search_engine = "<p id='front-side' onclick='myFunction()'>Search Engine</p> <p id='back-side' onclick='myFunction_2()'>Search engine (SE) a program, which searches a document or group of documents for relevant matches of a users keyword phrase and returns a list of the most relevant matches. Internet search engines such as Google and Yahoo search the entire internet for relevant matches.</p>";

var search_engine_spam = "<p id='front-side' onclick='myFunction()'>Search Engine Spam</p> <p id='back-side' onclick='myFunction_2()'>Search engine spam Pages created to cause search engines to deliver inappropriate or less relevant results. Search Engine Optimizers are sometimes unfairly perceived as search engine Spammers. Of course in some cases they actually are.</p>";

var SEM = "<p id='front-side' onclick='myFunction()'>Search engine marketing (SEM)</p> <p id='back-side' onclick='myFunction_2()'>SEM stands for Search Engine Marketing. In other words it means 'marketing via search engines'. Marketing or promoting your products or services via search engines can be done in two main ways. You either optimize your site so it appears at a high spot in organic search results, or pay for the clicks directly, in which case your site is listed under the 'sponsored listings' section.</p>";

var SEO = "<p id='front-side' onclick='myFunction()'>SEO Search Engine Optimization</p> <p id='back-side' onclick='myFunction_2()'>Short for search engine optimization, the process of increasing the number of visitors to a Web site by achieving high rank in the search results of a search engine. The higher a Web site ranks in the results of a search, the greater the chance that users will visit the site. It is common practice for Internet users to not click past the first few pages of search results, therefore high rank in SERPs is essential for obtaining traffic for a site. SEO helps to ensure that a site is accessible to a search engine and improves the chances that the site will be indexed and favorably ranked by the search engine.</p>";

var SERP = "<p id='front-side' onclick='myFunction()'>SERPs (Search Engine Results Pages)</p> <p id='back-side' onclick='myFunction_2()'>SERP stands for Search Engine Results Page (SERPs - Search Engine Results Pages). This is a page that gets displayed when you search for a keyword on Google or other search engine.</p>";

var site_map = "<p id='front-side' onclick='myFunction()'>Site map</p> <p id='back-side' onclick='myFunction_2()'>A page or structured group of pages which link to every user accessible page on a website, and hopefully improves site usability by clarifying the data structure of the site for the users. An XML sitemap is often kept in the root directory of a site just to help search engine spiders to find all of the site pages.</p>";

var social_bookmark = "<p id='front-side' onclick='myFunction()'>Social Bookmark</p> <p id='back-side' onclick='myFunction_2()'>A form of Social Media where users bookmarks are aggregated for public access.</p>";

var social_media = "<p id='front-side' onclick='myFunction()'>Social Media</p> <p id='back-side' onclick='myFunction_2()'>Various online technologies used by people to share information and perspectives. Blogs, wikis, forums, social bookmarking, user reviews and rating sites (digg, reddit) are all examples of Social Media.</p>";

var SMM = "<p id='front-side' onclick='myFunction()'>Social media marketing (SMM)</p> <p id='back-side' onclick='myFunction_2()'>Website or brand promotion through social media</p>";

var SpamAd = "<p id='front-side' onclick='myFunction()'>spam ad page (SpamAd page</p> <p id='back-side' onclick='myFunction_2()'>A Made For Adsense/Advertisement page which uses scraped or machine generated text for content, and has no real value to users other than the slight value of the adds. Spammers sometimes create sites with hundreds of these pages.</p>";

var spamdexing = "<p id='front-side' onclick='myFunction()'>Spamdexing</p> <p id='back-side' onclick='myFunction_2()'>Spamdexing or search engine spamming is the practice of deceptively modifying web pages to increase the chance of them being placed close to the beginning of search engine results, or to influence the category to which the page is assigned in a dishonest manner</p>";

var spammer = "<p id='front-side' onclick='myFunction()'>Spammer</p> <p id='back-side' onclick='myFunction_2()'>A person who uses spam to pursue a goal.</p>";

var spider_trap = "<p id='front-side' onclick='myFunction()'>Spider Trap</p> <p id='back-side' onclick='myFunction_2()'>Spider trap an endless loop of automatically generated links which can 'trap' a spider program. Sometimes intentionally used to prevent automated scraping or e-mail address harvesting.</p>";

var splash_pages = "<p id='front-side' onclick='myFunction()'>Splash Pages</p> <p id='back-side' onclick='myFunction_2()'>Often animated, graphics pages without significant textual content. Splash pages are intended to look flashy to humans, but without attention to SEO may look like dead ends to search engine spiders, which can only navigate through text links. Poorly executed splash pages may be bad for SEO and often a pain in the ass for users.</p>";

var splog = "<p id='front-side' onclick='myFunction()'>Splog</p> <p id='back-side' onclick='myFunction_2()'>Spam Blog which usually contains little if any value to humans, and is often machine generated or made up of scraped content.</p>";

var static_page = "<p id='front-side' onclick='myFunction()'>Static Page</p> <p id='back-side' onclick='myFunction_2()'>A web page without dynamic content or variables such as session IDs in the URL. Static pages are good for SEO work in that they are friendly to search engine spiders.</p>";

var stickiness = "<p id='front-side' onclick='myFunction()'>Stickiness </p> <p id='back-side' onclick='myFunction_2()'>Mitigation of bounce rate. Website changes that entice users to stay on the site longer, and view more pages improve the sites 'stickiness'.</p>";

var time_on_page = "<p id='front-side' onclick='myFunction()'>Time On Page</p> <p id='back-side' onclick='myFunction_2()'>The amount of time that a user spends on one page before clicking off. An indication of quality and relevance.</p>";

var trust_rank = "<p id='front-side' onclick='myFunction()'>Trust Rank</p> <p id='back-side' onclick='myFunction_2()'>A method of differentiating between valuable pages and spam by quantifying link relationships from trusted human evaluated seed pages.</p>";

var URL = "<p id='front-side' onclick='myFunction()'>URL</p> <p id='back-side' onclick='myFunction_2()'>A Uniform Resource Locator, colloquially termed a web address, is a reference to a web resource that specifies its location on a computer network and a mechanism for retrieving it. A URL is a specific type of Uniform Resource Identifier, although many people use the two terms interchangeably.</p>";

var UGC = "<p id='front-side' onclick='myFunction()'>User generated content (UGC)</p> <p id='back-side' onclick='myFunction_2()'>Social Media, wikis, Folksonomies, and some blogs rely heavily on User Generated Content. One could say that Google is exploiting the entire web as UGC for an advertising venue.</p>";

var walled_garden = "<p id='front-side' onclick='myFunction()'>Walled Garden</p> <p id='back-side' onclick='myFunction_2()'>A group of pages which link to each other, but are not linked to by any other pages. A walled garden can still be indexed if it is included in a sitemap, but it will probably have very low pagerank.</p>";

var white_hat = "<p id='front-side' onclick='myFunction()'>White Hat SEO</p> <p id='back-side' onclick='myFunction_2()'>SEO techniques, which conform to best practice guidelines, and do not attempt to unscrupulously 'game' or manipulate SERPs.</p>";

var skyrim = "<p id='front-side' onclick='myFunction()'>What is the capitol of Skyrim?</p> <p id='back-side' onclick='myFunction_2()'>Solitude</p>";

var nega_key = "<p id='front-side' onclick='myFunction()'>Negative Keywords</p> <p id='back-side' onclick='myFunction_2()'>In pay per click advertising (PPC), negative keywords prevent advertisements from displaying for particular keyword phrases. </p>";

var keyword_grouping = "<p id='front-side' onclick='myFunction()'>Keyword Grouping or Keyword Clustering</p> <p id='back-side' onclick='myFunction_2()'>You are taking relevant keywords and clustering them together into groups. Those groups work together to give your website a more thoroughly categorized theme, which in turn helps to establish its purpose and attract those crawlers that tell Google that page is one they should bump up the list. </p>";

var dynamic_url = "<p id='front-side' onclick='myFunction()'>Dynamic URL</p> <p id='back-side' onclick='myFunction_2()'>A URL that results from the search of a database-driven Web site or the URL of a Web site that runs a script. In contrast to static URLs, in which the contents of the Web page do not change unless the changes are coded into the HTML, dynamic URLs are generated from specific queries to a site's database. The page is merely a template to display the results of the query. Most of the content comes from the database that is associated with the site. Instead of changing information in the HTML code, the data is changed in the database. </p>";

var pogo_sticking = "<p id='front-side' onclick='myFunction()'>Pogo Sticking</p> <p id='back-side' onclick='myFunction_2()'>Pogo-sticking is defined as going back and forth from a search engine results page (SERP) to an individual search result destination site. In other words, pogo-sticking is when the searcher clicks on a link on a SERP, sees that it's not what she is looking for, and immediately bounces off by hitting the back button.</p>";

var local_search = "<p id='front-side' onclick='myFunction()'>Local Search</p> <p id='back-side' onclick='myFunction_2()'>Local search is the use of specialized Internet search engines that allow users to submit geographically constrained searches against a structured database of local business listings</p>";

var bert = "<p id='front-side' onclick='myFunction()'>BERT</p> <p id='back-side' onclick='myFunction_2()'>The BERT algorithm (Bidirectional Encoder Representations from Transformers) is a deep learning algorithm related to natural language processing. It helps a machine to understand what words in a sentence mean, but with all the nuances of context.</p>";

var campaign_ga = "<p id='front-side' onclick='myFunction()'>Campiagn</p> <p id='back-side' onclick='myFunction_2()'>An ad campaign on Google AdWords is made up of your ad groups, and has the same budget, campaign type and your other ad settings. It’s generally what you first set-up when you advertise, and it helps you organize your different paid advertising efforts. You can run multiple campaigns at any time from your Google account.</p>";

var ad_groups = "<p id='front-side' onclick='myFunction()'>Ad groups</p> <p id='back-side' onclick='myFunction_2()'>An ad group is your set of keywords, budgets and targeting methods for a particular objective, within the same campaign. For example, if you are running an ad campaign for a shoe sale, you could set up ad groups to target for online sales, women’s shoes and men’s shoes. You can have multiple ads in each ad group.</p>";

var campaign_type = "<p id='front-side' onclick='myFunction()'>Campaign Type</p> <p id='back-side' onclick='myFunction_2()'>Your campaign type is where you want your ads to be seen. Google has:<ul><li>'Search Network only' (which means Google search only)</li><li>'Display Network only' (which means your ad shows up in Google’s Display network of websites, videos, YouTube, Blogger and more. This is also known as AdSense)</li><li>'Search Network with Display Select' (which is a combo of search and display)</li></ul> If you have a Google Merchant Center account and want to use Product Listing Ads, you can also choose “Shopping” as a campaign type.</p>";

var keywords_ga = "<p id='front-side' onclick='myFunction()'>Keywords</p> <p id='back-side' onclick='myFunction_2()'>Keywords are very important in your Google Ads. They are the words or word phrases you choose for your ads, and will help to determine where and when your ad will appear. When choosing your keywords, think like your customer and what they would be searching for when they want your product, service or offer. Though you can include as many as you like, I suggest a maximum of twenty keywords.</p>";

var quality_score = "<p id='front-side' onclick='myFunction()'>Quality Score</p> <p id='back-side' onclick='myFunction_2()'>A quality score is the measurement from Google based on the relevancy of your ad headline, description, keywords and destination URL to your potential customer seeing your ad. A higher Quality Score can get you better ad placement and lower costs.</p>";

var impressions_ga = "<p id='front-side' onclick='myFunction()'>Impressions</p> <p id='back-side' onclick='myFunction_2()'>An impression is the measurement of how many times your ad is shown.</p>";

var ad_rank_ga = "<p id='front-side' onclick='myFunction()'>Ad Rank</p> <p id='back-side' onclick='myFunction_2()'>Your Ad Rank is the value that’s used to determine where your ad shows up on a page. It’s based on your Quality Score and your bid amount.</p>";

var mobile_ads_ga = "<p id='front-side' onclick='myFunction()'>Mobile ad</p> <p id='back-side' onclick='myFunction_2()'>Mobile ads are what your mobile searchers see on their devices. Google AdWords has WAP mobile ads and 'ads for high-end mobile devices'.</p>";

var ad_extensions = "<p id='front-side' onclick='myFunction()'>Ad extensions</p> <p id='back-side' onclick='myFunction_2()'>Ad extensions are extra information about your business, such as your local address, phone number, and even coupons or additional websites. They’re what shows up in blue below your ad descriptions.</p>";

var cta_ga = "<p id='front-side' onclick='myFunction()'>Call to Action (CTA)</p> <p id='back-side' onclick='myFunction_2()'>A CTA is literally the action you want your searcher to take. Good CTAs in your ads are short, action oriented words such as 'Buy', 'Get','Act Now', etc.</p>";

var ctr_ga = "<p id='front-side' onclick='myFunction()'>Click Through Rate (CTR)</p> <p id='back-side' onclick='myFunction_2()'>Your CTR is an important metric in your account settings. It measures how many people who have seen your ad click through to your link destination.</p>";

var landing_page_ga = "<p id='front-side' onclick='myFunction()'>Landing Page</p> <p id='back-side' onclick='myFunction_2()'>Your landing page is the page on your website to which you’re driving traffic from your ad.</p>";

var optimization_ga = "<p id='front-side' onclick='myFunction()'>Optimization</p> <p id='back-side' onclick='myFunction_2()'>Optimization in Google AdWords is like optimization elsewhere in marketing. It means making the changes in your ad that get you higher results for your objectives.</p>";

var split_testing_ga = "<p id='front-side' onclick='myFunction()'>Split Testing</p> <p id='back-side' onclick='myFunction_2()'>Split testing includes A/B and multivariate testing. It's a method of controlled marketing experiments with the goal being to improve your objective results (such as higher CTR's, increased conversion or even better Ad Ranking).</p>";

var bid_strat_ga = "<p id='front-side' onclick='myFunction()'>Bid Strategy</p> <p id='back-side' onclick='myFunction_2()'>Your bid strategy is basically how you set your bid type to pay for viewer interaction with your ads.</p>";

var daily_budget = "<p id='front-side' onclick='myFunction()'>Daily budget</p> <p id='back-side' onclick='myFunction_2()'>Your daily budget is what you're willing to spend per day per ad.  Your daily cost is based on a daily average per month, so don’t be alarmed if yours varies from day to day.</p>";

var cpc_ppc_ga = "<p id='front-side' onclick='myFunction()'>CPC and PPC</p> <p id='back-side' onclick='myFunction_2()'>Cost-Per-Click is the most common bid type on Google AdWords. It means you pay every time a person actually clicks on your ad. You set your 'maximum CPC' in the bidding process, which means that dollar amount is the most you'll pay for a click on your ad. Pay-Per-Click is the same as CPC.</p>";

var cpm_ga = "<p id='front-side' onclick='myFunction()'>CPM </p> <p id='back-side' onclick='myFunction_2()'>Cost-Per-thousand impressions is a bidding method that bases your costs on how many times your ads are shown (impressions).</p>";

var billing_threshold_ga = "<p id='front-side' onclick='myFunction()'>Billing Threshold</p> <p id='back-side' onclick='myFunction_2()'>Your billing threshold is the level of spending that triggers a charge to you for the ad costs. It applies to automatic payments, and the threshold level starts at $50. It you reach that within 30 days, you’ll be billed, and your threshold then raises to $100 and so on.</p>";

var headline_ga = "<p id='front-side' onclick='myFunction()'>Headline</p> <p id='back-side' onclick='myFunction_2()'>Your ad headline is the header of your ad copy.  It generally shows up in blue when your ad is live.</p>";

var destination_url_ga = "<p id='front-side' onclick='myFunction()'>Destination URL</p> <p id='back-side' onclick='myFunction_2()'>Your destination URL is the landing page your ad is directed to when it's clicked. Your destination site can be a specific page. You can change it for differing ads within ad groups. Your audience does not see it in the ad.</p>";

var display_url_ga = "<p id='front-side' onclick='myFunction()'>Display URL</p> <p id='back-side' onclick='myFunction_2()'>Your display URL is what shows up in your ad copy. You can keep this simple and clean to increase your brand recognition, trust, and conversions.</p>";

var side_ad_ga = "<p id='front-side' onclick='myFunction()'>Side ad</p> <p id='back-side' onclick='myFunction_2()'>A side ad is the ad that show up on the right hand side of a search engine results page (SERP). Note: Your ad will likely show up as both a side ad and a top ad - so write your ad copy to optimize for both.</p>";

var top_ad_ga = "<p id='front-side' onclick='myFunction()'>Top ad</p> <p id='back-side' onclick='myFunction_2()'>A top ad is the ad that shows up in a shaded box above the organic search results. Note: Your ad will likely show up as both a side ad and a top ad - so write your ad copy to optimize for both.</p>";

var eat_seo = "<p id='front-side' onclick='myFunction()'>E-A-T</p> <p id='back-side' onclick='myFunction_2()'>E-A-T stands for 'Expertise, Authoritativeness, Trustworthiness.'<br></br>'Expertise' – You need to be an expert in your field. Expertise means you need to show the skill of the creator for the Main Content or (MC) and mention it in your content. Expertise is less critical for humor or gossip websites, but it’s vital for medical, financial, or legal websites. The good news is any site can show expertise if the content is truthful and useful for users.<br></br>'Authoritativeness' – You need to show that you are an authority or the authoritativeness of the creator for the MC. And you can get this from the expertise of your writers or your self. If your page is a community or forum discussion, the quality of the conversation drives authority. Credentials are necessary, but so are personal experiences like reviews.<br></br>'Trustworthiness' – You need to show users they can trust the creator or company of the Main Content, the MC itself and the website. Trustworthiness is especially important for eCommerce websites that ask users for their credit card information. Everything about your site should make users feel safe while they’re visiting. As a starting point, you should immediately implement an SSL certificate on your site as at least 70% of first page results are using SSL (It’s one of many of Googles scoring signals)</p>";

var ymyl_seo = "<p id='front-side' onclick='myFunction()'>YMYL</p> <p id='back-side' onclick='myFunction_2()'>YMYL is the acronym of “Your Money or Your Life.” According to Google, any page that includes quality content about future happiness, health, safety, investment or financial stability is a YMYL page. That means if you have a blog that gives health advice, it is a YMYL page.</p>";

var rank_brain = "<p id='front-side' onclick='myFunction()'>RankBrain</p> <p id='back-side' onclick='myFunction_2()'>RankBrain is Google’s name for a machine-learning artificial intelligence system that’s used to help process its search results, as was reported by Bloomberg and also confirmed to us by Google.</p>";

var local_seo = "<p id='front-side' onclick='myFunction()'>Local SEO</p> <p id='back-side' onclick='myFunction_2()'>Local SEO (Local Search Engine Optimization), sometimes referred to as local search engine marketing, is an incredibly effective way to market your local business online, as it helps businesses promote their products and services to local customers at the exact time they’re looking for them online.<br><br>This is achieved through a variety of methods, some of which differ greatly from what’s practiced in standard SEO, and some of which are far easier to manage using local SEO tools and can require specific local SEO services.</p>";

var disavow = "<p id='front-side' onclick='myFunction()'>Disavow Tool</p> <p id='back-side' onclick='myFunction_2()'>Definition: The Disavow tool is part of Google Search Console (formerly Webmaster Tools) that allows websites to discount the value of an inbound link, helping to prevent against link-based penalties. Google's war on link spam puts some online businesses at risk of organic search penalty, making the disavow tool an important asset for websites at risk of being penalized.</p>";

var crawl_budget = "<p id='front-side' onclick='myFunction()'>Disavow Tool</p> <p id='back-side' onclick='myFunction_2()'>Crawl Budget is the number of pages Googlebot crawls and indexes on a website within a given timeframe. <br><br>In short: if Google doesn’t index a page, it’s not going to rank for anything. <br><br>So if your number of pages exceed your site’s crawl budget, you’re going to have pages on your site that aren’t indexed. That said, there are a few cases where you do want to pay attention to crawl budget:<br><br>You run a big site: If you have a website (like an ecommerce site) with 10k+ pages, Google can have trouble finding them all.<br>You just added a bunch of pages: If you recently added a new section to your site with hundreds of pages, you want to make sure that you have the crawl budget to get them all indexed quickly.<br>Lots of redirects: Lots of redirects and redirect chains eat up your crawl budget.</p>";

var strut_data = "<p id='front-side' onclick='myFunction()'>Structured Data</p> <p id='back-side' onclick='myFunction_2()'>Structured data refers to any data that resides in a fixed field within a record or file. This includes data contained in relational databases and spreadsheets.<br><br>Structured data first depends on creating a data model – a model of the types of business data that will be recorded and how they will be stored, processed and accessed. This includes defining what fields of data will be stored and how that data will be stored: data type (numeric, currency, alphabetic, name, date, address) and any restrictions on the data input (number of characters; restricted to certain terms such as Mr., Ms. or Dr.; M or F).<br><br>Structured data has the advantage of being easily entered, stored, queried and analyzed. At one time, because of the high cost and performance limitations of storage, memory and processing, relational databases and spreadsheets using structured data were the only way to effectively manage data. Anything that couldn't fit into a tightly organized structure would have to be stored on paper in a filing cabinet.</p>";

var mixed_content = "<p id='front-side' onclick='myFunction()'>Mixed Content Warning</p> <p id='back-side' onclick='myFunction_2()'>Mixed content occurs when initial HTML is loaded over a secure HTTPS connection, but other resources (such as images, videos, stylesheets, scripts) are loaded over an insecure HTTP connection. This is called mixed content because both HTTP and HTTPS content are being loaded to display the same page, and the initial request was secure over HTTPS. Modern browsers display warnings about this type of content to indicate to the user that this page contains insecure resources.</p>";

var tld = "<p id='front-side' onclick='myFunction()'>TLD (top-level domain)</p> <p id='back-side' onclick='myFunction_2()'>Top-level domain (TLD) refers to the last segment of a domain name or the part that follows immediately after the 'dot' symbol.<br>There are 5 types of TLDs:<br>Generic (international) Top-Level Domains (gTLD) – com, edu, org, net, etc.<br>Country-Code Top-Level Domains (ccTLD) – co.uk, ca, au, etc.<br>Sponsored Top-Level Domains (sTLD) – museum, aero, etc.<br>Infrastructure Top-Level Domains – .arpa<br>Test top-level domains (tTLD) – test</p>";

var att_modeling = "<p id='front-side' onclick='myFunction()'>Attribution Modeling</p> <p id='back-side' onclick='myFunction_2()'>An attribution model is the rule, or set of rules, that determines how credit for sales and conversions is assigned to touchpoints in conversion paths. For example, the Last Interaction model in Analytics assigns 100% credit to the final touchpoints (i.e., clicks) that immediately precede sales or conversions. In contrast, the First Interaction model assigns 100% credit to touchpoints that initiate conversion paths.<br><br>You can use the Multi-Channel Funnels Model Comparison Tool to compare how different attribution models impact the valuation of your marketing channels. In the tool, the calculated Conversion Value (and the number of conversions) for each of your marketing channels will vary according to the attribution model used. A channel that predominantly initiates conversion paths will have a higher Conversion Value according to the First Interaction attribution model than it would according to the Last Interaction attribution model.</p>";

var thin_content = "<p id='front-side' onclick='myFunction()'>Thin Content</p> <p id='back-side' onclick='myFunction_2()'>Thin content is content that has little or no value to the user. Google considers doorway pages, low-quality affiliate pages, or simply pages with very little or no content as thin content pages. But don’t fall into the trap of just producing loads of very similar content: non-original pages, pages with scraped and duplicate content, are considered thin content pages too. On top of that, Google doesn’t like pages that are stuffed with keywords either. Google has gotten smarter and has learned to distinguish between valuable and low-quality content, especially since Google Panda.</p>";




var myArray = [redirect, Google_Ads, Affiliate, algorithm, Google_Analytics, anchor_text, astroturfing, authority_site, b2b_b2c, backlink_word, black_hat_seo, blog, bot, bounce_rate, bread_crumbs, canonical_tag, click_fraud, cloaking, cms_crm, code_swapping, comment_spam, conversion_rate, conversion, cpc, cpm, directory, doorway, duplicate_content, feed, link_farm, frames, gizmo, google_bomb, google_bowling, google_dance, google_juice, hit, hub, HTML, impressions, inbound_link, index, indexed_pages, keyword_cannibalization, keyword_density, keyword_research, keyword_stuffing, landing_page, lsi, link, link_bait, link_building, linkerati, Link_Condom, link_exchange, link_love, link_partner, link_popularity, long_tail, mashups, meta_tags, metric, mirror_site, monetize, natural_search_results, nofollow, noindex, non_reciprocal_link, organic_link, pagerank, paid_inclusion, portal, PPA, PPC, Proprietary_Method, RLT, robots, ROI, sandbox, search_engine, search_engine_spam, SEM, SEO, site_map, SERP, social_bookmark, social_media, SMM, spamdexing, SpamAd, spammer, spider_trap, splash_pages, splog, static_page, stickiness, time_on_page, trust_rank, URL, UGC, white_hat, skyrim, nega_key, keyword_grouping, dynamic_url, local_search, pogo_sticking, bert, campaign_ga, ad_groups, campaign_type, keywords_ga, quality_score, impressions_ga, ad_rank_ga, mobile_ads_ga, ad_extensions, cta_ga, ctr_ga, landing_page_ga, optimization_ga, split_testing_ga, bid_strat_ga, daily_budget, cpc_ppc_ga, cpm_ga, billing_threshold_ga, headline_ga, destination_url_ga, display_url_ga, side_ad_ga, top_ad_ga, eat_seo, ymyl_seo, rank_brain, local_seo, disavow, crawl_budget, strut_data, mixed_content, tld, att_modeling, thin_content];

var randomItem = myArray[Math.floor(Math.random()*myArray.length)];

document.getElementById("demo").innerHTML = randomItem;

function GetValue() {
	var randomItem = myArray[Math.floor(Math.random()*myArray.length)];
	document.getElementById("demo").innerHTML = randomItem;
}

function myFunction() {
    document.getElementById("back-side").style.display = "block ";
    document.getElementById("front-side").style.display = "none ";
}

function myFunction_2() {
    document.getElementById("back-side").style.display = "none ";
    document.getElementById("front-side").style.display = "block ";
}

